### ISSUE TITLE
请问train_ner.py中model = load_model('../data/model/ner_model.h5', custom_objects=get_custom_objects())的../data/model/ner_model.h5需要从哪下载

### ISSUE THREAD

**Issue by yuanhuachao** [duterscmy/ccks2019-ckbqa-4th-codes#39]

**Comment by HankTown** [comment]
你好，请问你找到答案了吗？

**Comment by duterscmy** [comment]
把这行注释掉，第一次运行没有模型需要训练。 在2020年11月19日 11:03，hank 写道： 

你好，请问你找到答案了吗？



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/duterscmy/ccks2019-ckbqa-4th-codes/issues/39#issuecomment-730095990",

"url": "https://github.com/duterscmy/ccks2019-ckbqa-4th-codes/issues/39#issuecomment-730095990",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by HankTown** [comment]
> 把这行注释掉，第一次运行没有模型需要训练。 在2020年11月19日 11:03，hank 写道： 你好，请问你找到答案了吗？ —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe. [ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "[#39 (comment)](https://github.com/duterscmy/ccks2019-ckbqa-4th-codes/issues/39#issuecomment-730095990)", "url": "[#39 (comment)](https://github.com/duterscmy/ccks2019-ckbqa-4th-codes/issues/39#issuecomment-730095990)", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

谢谢，果然可以了
